version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_INITDB_ARGS=--max_wal_size=2GB
    ports:
      - "5432:5432"
    volumes:
      - beacon_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      options:
        max-size: "25m"
        max-file: "2"

  migrate:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push"
    networks:
      - app-network

  beacon-fetch:
    container_name: fetch
    env_file:
      - .env
    build:
      context: .
      dockerfile: packages/beacon-fetch/Dockerfile
    depends_on:
      - migrate
    networks:
      - app-network

  bot:
    container_name: bot
    env_file:
      - .env
    build:
      context: .
      dockerfile: packages/telegram-bot/Dockerfile
    depends_on:
      - beacon-fetch
    networks:
      - app-network
    logging:
      options:
        max-size: "25m"
        max-file: "2"

networks:
  app-network:
    driver: bridge

volumes:
  beacon_postgres_data:
